import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import CustomHeader from './components/common/CustomHeader';
import SidebarLeft from './components/common/SidebarLeft';
import { DisplaySettings } from '@mui/icons-material';
import SidebarRight from './components/common/SidebarRight';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className='wrapper'>
          <CustomHeader title='Welcome to My App'></CustomHeader>
          <div className='flex'>
            <SidebarLeft />
            <div className='main'>{children}</div>
            <SidebarRight />
          </div>
        </div>
      </body>
    </html>
  );
}
